server:
  port: 9011
  servlet:
    context-path: /
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/manik
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true


logging:
  level:
    org.hibernate: DEBUG


springdoc:
  packagesToScan: com.msig.transaction
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /doc/api-docs
