spring:
  devtools:
    restart:
      enabled: 'true'
      poll-interval: '2s'
      quiet-period: '1s'
      additional-paths:
        - src/main/java/
  application:
    name: transaction-service
  config:
    import: "optional:configserver:http://localhost:9999"
